# Generated by Django 3.2 on 2021-05-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_produto_nomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nomes',
            new_name='nome',
        ),
    ]
